// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PNIWeb.Model.Models;

public partial class bd_PNIContext : DbContext
{
    public bd_PNIContext()
    {
    }

    public bd_PNIContext(DbContextOptions<bd_PNIContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TbBiblioteca> TbBiblioteca { get; set; }

    public virtual DbSet<TbLogin> TbLogin { get; set; }

    public virtual DbSet<TbPesquisa> TbPesquisa { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)        
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-NLVN3AE;Initial Catalog=bd_PNI;User ID=sa;Password=sa123; TrustServerCertificate=True");

    //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //=> optionsBuilder.UseSqlServer("Data Source=DESKTOP-NLVN3AE;Initial Catalog=bd_PNI;User ID=sa;Password=sa123; TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TbBiblioteca>(entity =>
        {
            entity.HasKey(e => e.BibId).HasName("PK__tb_Bibli__6C5294E48E713DAA");
        });

        modelBuilder.Entity<TbLogin>(entity =>
        {
            entity.HasKey(e => e.LgId).HasName("PK__tb_Login__8C6ECABBD3797323");
        });

        modelBuilder.Entity<TbPesquisa>(entity =>
        {
            entity.HasKey(e => e.PqId).HasName("PK__tb_Pesqu__4EC8832132C27FE9");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}