// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PNIWeb.Model.Models;

[Table("tb_Biblioteca")]
public partial class TbBiblioteca
{
    [Key]
    [Column("bib_Id")]
    public int BibId { get; set; }

    [Required]
    [Column("bib_Autor")]
    [StringLength(30)]
    [Unicode(false)]
    public string BibAutor { get; set; }

    [Required]
    [Column("bib_Editora")]
    [StringLength(10)]
    [Unicode(false)]
    public string BibEditora { get; set; }

    [Required]
    [Column("bib_Titulo")]
    [StringLength(20)]
    [Unicode(false)]
    public string BibTitulo { get; set; }

    [Column("bib_Capa")]
    public bool? BibCapa { get; set; }

    [Column("bib_DataPubli", TypeName = "date")]
    public DateTime? BibDataPubli { get; set; }

    [Column("bib_Fk")]
    public int? BibFk { get; set; }
}