// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PNIWeb.Model.Models;

[Table("tb_Login")]
public partial class TbLogin
{
    [Key]
    [Column("lg_Id")]
    public int LgId { get; set; }

    [Required]
    [Column("lg_Nome")]
    [StringLength(30)]
    [Unicode(false)]
    public string LgNome { get; set; }

    [Column("lg_Email")]
    [StringLength(20)]
    [Unicode(false)]
    public string LgEmail { get; set; }

    [Column("lg_Cpf")]
    public int LgCpf { get; set; }

    [Required]
    [Column("lg_Unidade")]
    [StringLength(20)]
    [Unicode(false)]
    public string LgUnidade { get; set; }

    [Column("lg_Fk")]
    public int? LgFk { get; set; }
}