// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PNIWeb.Model.Models;

[Table("tb_Pesquisa")]
public partial class TbPesquisa
{
    [Key]
    [Column("pq_Id")]
    public int PqId { get; set; }

    [Column("pq_Entrada", TypeName = "datetime")]
    public DateTime PqEntrada { get; set; }

    [Column("pq_Saida", TypeName = "datetime")]
    public DateTime PqSaida { get; set; }

    [Required]
    [Column("pq_Nome")]
    [StringLength(30)]
    [Unicode(false)]
    public string PqNome { get; set; }

    [Required]
    [Column("pq_Titulo")]
    [StringLength(50)]
    [Unicode(false)]
    public string PqTitulo { get; set; }

    [Required]
    [Column("pq_Instituicao")]
    [StringLength(40)]
    [Unicode(false)]
    public string PqInstituicao { get; set; }

    [Column("pq_Fk")]
    public int? PqFk { get; set; }
}